### ISSUE TITLE
can not serve graphiql's static files

### ISSUE THREAD

**Issue by lee-garden** [paywteam/npoem-server#20]
![image](https://user-images.githubusercontent.com/41745717/82899695-606eb400-9f96-11ea-9fc6-77f8e2245709.png)

**Comment by lee-garden** [comment]
i will search WebMVC configuration

**Comment by YooInKeun** [comment]
Ok, I will contact you after checking by tomorrow.

**Comment by YooInKeun** [comment]
#23 solves this problem. I suggest removing `WebConfig.java` and setting cors config on `WebSecurityConfig.java`. Thank you :)
